---
openapi: 3.0.1
info:
  title: Images repository API documentation
  version: v1
paths:
  "/images/{id}":
    get:
      summary: Retrieves an image
      tags:
      - Images
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: image found
servers:
- url: https://shopify-image-repository.herokuapp.com
