---
openapi: 3.0.1
info:
  title: Images repository API documentation
  version: v1
  description: This is the API documentation of the images repository at https://github.com/charbeltabet/shopify-image-repository
paths:
  "/users/{user_id}/granted_accesses":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list granted_accesses
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
    post:
      summary: create granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
    delete:
      summary: destroy_all granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
  "/users/{user_id}/granted_accesses/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
    patch:
      summary: update granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
    put:
      summary: update granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
    delete:
      summary: delete granted_access
      tags:
      - User's Image Granted Accesses
      responses:
        '200':
          description: successful
  "/images/{image_id}/transfer_ownership":
    parameters:
    - name: image_id
      in: path
      description: image_id
      required: true
      schema:
        type: string
    post:
      summary: transfer_ownership image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images/{image_id}/publicize":
    parameters:
    - name: image_id
      in: path
      description: image_id
      required: true
      schema:
        type: string
    post:
      summary: publicize image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images/{image_id}/privatize":
    parameters:
    - name: image_id
      in: path
      description: image_id
      required: true
      schema:
        type: string
    post:
      summary: privatize image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images/{mode}/{unique_name}":
    parameters:
    - name: mode
      in: path
      description: mode
      required: true
      schema:
        type: string
    - name: unique_name
      in: path
      description: unique_name
      required: true
      schema:
        type: string
    get:
      summary: view image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images":
    get:
      summary: list images
      tags:
      - Images
      responses:
        '200':
          description: successful
    post:
      summary: create image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show image
      tags:
      - Images
      responses:
        '200':
          description: successful
    patch:
      summary: update image
      tags:
      - Images
      responses:
        '200':
          description: successful
    put:
      summary: update image
      tags:
      - Images
      responses:
        '200':
          description: successful
    delete:
      summary: delete image
      tags:
      - Images
      responses:
        '200':
          description: successful
  "/images/{image_id}/protected_actions":
    parameters:
    - name: image_id
      in: path
      description: image_id
      required: true
      schema:
        type: string
    get:
      summary: list protected_actions
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
    post:
      summary: create protected_action
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
  "/images/{image_id}/protected_actions/{id}":
    parameters:
    - name: image_id
      in: path
      description: image_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show protected_action
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
    patch:
      summary: update protected_action
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
    put:
      summary: update protected_action
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
    delete:
      summary: delete protected_action
      tags:
      - Images Protected Actions
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - Users
      responses:
        '200':
          description: successful
    put:
      summary: update user
      tags:
      - Users
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
